#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: AnySearch MCP + Skill installer
# Docs: https://www.anysearch.com/docs/auth
#       https://www.anysearch.com/docs/mcp-install
#       https://www.anysearch.com/docs/skill-install
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

ANYSEARCH_HOME="${ANYSEARCH_HOME:-$HOME/.anysearch}"
ANYSEARCH_MCP_URL="https://api.anysearch.com/mcp"
SKILL_ZIP_URL="https://github.com/anysearch-ai/anysearch-skill/archive/refs/heads/main.zip"
CURSOR_MCP_JSON="${CURSOR_MCP_JSON:-$HOME/.cursor/mcp.json}"

_install_skill_to() {
  local dest="$1"
  local tmp extract_root
  mkdir -p "$(dirname "$dest")"
  tmp=$(mktemp -d)
  say "Downloading skill → $dest"
  curl -fsSL -o "$tmp/anysearch-skill.zip" "$SKILL_ZIP_URL"
  unzip -q "$tmp/anysearch-skill.zip" -d "$tmp"
  extract_root=$(find "$tmp" -maxdepth 1 -type d -name 'anysearch-skill-*' | head -n1)
  if [[ -z "$extract_root" || ! -f "$extract_root/SKILL.md" ]]; then
    warn "unexpected zip layout; aborting skill install to $dest"
    rm -rf "$tmp"
    return 1
  fi
  rm -rf "$dest"
  mkdir -p "$dest"
  # Prefer nested package if present; else whole extract root
  if [[ -d "$extract_root/anysearch" && -f "$extract_root/anysearch/SKILL.md" ]]; then
    cp -R "$extract_root/anysearch/." "$dest/"
  else
    cp -R "$extract_root/." "$dest/"
  fi
  rm -rf "$tmp"
  printf '  %s✓ skill installed%s %s\n' "$GREEN" "$RESET" "$dest"
}

_write_skill_env() {
  local dest="$1" key="$2"
  local prev="$ENV_FILE"
  ENV_FILE="$dest/.env"
  write_env ANYSEARCH_API_KEY "$key"
  ENV_FILE="$prev"
}

_upsert_cursor_mcp() {
  local key="$1"
  python3 - "$CURSOR_MCP_JSON" "$key" "$ANYSEARCH_MCP_URL" <<'PY'
import json, os, sys
path, key, url = sys.argv[1], sys.argv[2], sys.argv[3]
os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
data = {}
if os.path.isfile(path):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
servers = data.setdefault("mcpServers", {})
servers["anysearch"] = {
    "command": "npx",
    "args": [
        "-y",
        "mcp-remote",
        url,
        "--header",
        f"Authorization: Bearer {key}",
    ],
}
with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
print(path)
PY
}

banner "AnySearch setup (MCP + Skill)"

# ── 1. API key ────────────────────────────────────────────────────────────
stage "Get AnySearch API key"
say "Authenticated calls use: Authorization: Bearer <key>"
say "Invalid keys get 401/403 (no silent anonymous fallback)."
note "Docs: https://www.anysearch.com/docs/auth"
open_url "https://www.anysearch.com/console/api-keys"
step "Sign in if needed, create or reveal an API key, then copy it."
ENV_FILE="$ANYSEARCH_HOME/.env"
mkdir -p "$ANYSEARCH_HOME"
ask_secret ANYSEARCH_API_KEY "Paste your AnySearch API key:"
if [[ -z "${ANYSEARCH_API_KEY:-}" ]]; then
  warn "No key entered. Aborting — re-run when you have a key."
  exit 1
fi
write_env ANYSEARCH_API_KEY "$ANYSEARCH_API_KEY"

# ── 2. Choose targets ─────────────────────────────────────────────────────
stage "Choose where to install"
say "Default is YES for each target — press Enter to accept, or n to skip."
_pick() {
  local __var="$1" __prompt="$2" __reply=""
  printf '  %s? %s [Y/n] ' "$YELLOW" "$__prompt"
  read -r __reply || true
  if [[ "$__reply" =~ ^[Nn] ]]; then
    printf -v "$__var" '%s' 0
  else
    printf -v "$__var" '%s' 1
  fi
}
_pick INSTALL_CODEX "Install skill → ~/.codex/skills/anysearch"
_pick INSTALL_AGENTS "Install skill → ~/.agents/skills/anysearch"
_pick INSTALL_CURSOR_SKILL "Install skill → ~/.cursor/skills/anysearch"
_pick INSTALL_CURSOR_MCP "Configure Cursor MCP → ~/.cursor/mcp.json"
if (( INSTALL_CODEX + INSTALL_AGENTS + INSTALL_CURSOR_SKILL + INSTALL_CURSOR_MCP == 0 )); then
  warn "Nothing selected. Aborting."
  exit 1
fi

# ── 3. Install skill package ──────────────────────────────────────────────
stage "Install AnySearch skill"
say "Source: github.com/anysearch-ai/anysearch-skill (main.zip)"
if ! command -v unzip >/dev/null 2>&1; then
  warn "unzip is required"; exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
  warn "curl is required"; exit 1
fi
(( INSTALL_CODEX )) && _install_skill_to "$HOME/.codex/skills/anysearch" \
  && _write_skill_env "$HOME/.codex/skills/anysearch" "$ANYSEARCH_API_KEY"
(( INSTALL_AGENTS )) && _install_skill_to "$HOME/.agents/skills/anysearch" \
  && _write_skill_env "$HOME/.agents/skills/anysearch" "$ANYSEARCH_API_KEY"
(( INSTALL_CURSOR_SKILL )) && _install_skill_to "$HOME/.cursor/skills/anysearch" \
  && _write_skill_env "$HOME/.cursor/skills/anysearch" "$ANYSEARCH_API_KEY"

# ── 4. Cursor MCP ─────────────────────────────────────────────────────────
stage "Configure Cursor MCP"
if (( INSTALL_CURSOR_MCP )); then
  say "Using mcp-remote → $ANYSEARCH_MCP_URL (Bearer key)."
  note "Needs Node/npx available when Cursor starts the MCP server."
  out=$(_upsert_cursor_mcp "$ANYSEARCH_API_KEY")
  printf '  %s✓ upserted%s anysearch → %s\n' "$GREEN" "$RESET" "$out"
  say "Restart Cursor (or reload MCP) after this wizard finishes."
else
  note "Skipped Cursor MCP."
fi

# ── 5. Verify ─────────────────────────────────────────────────────────────
stage "Verify"
skill_dir=""
for d in \
  "$HOME/.codex/skills/anysearch" \
  "$HOME/.agents/skills/anysearch" \
  "$HOME/.cursor/skills/anysearch"
do
  [[ -d "$d/scripts" ]] && skill_dir="$d" && break
done
if [[ -n "$skill_dir" ]]; then
  export ANYSEARCH_API_KEY
  if command -v node >/dev/null 2>&1 && [[ -f "$skill_dir/scripts/anysearch_cli.js" ]]; then
    say "Running: node .../anysearch_cli.js doc"
    if node "$skill_dir/scripts/anysearch_cli.js" doc >/tmp/anysearch-verify.out 2>&1; then
      printf '  %s✓ entry test ok%s\n' "$GREEN" "$RESET"
      note "output: /tmp/anysearch-verify.out"
    else
      warn "entry test failed — see /tmp/anysearch-verify.out"
      SKIPPED+=("manual verify: node $skill_dir/scripts/anysearch_cli.js search \"hello\" --max_results 1")
    fi
  elif command -v python3 >/dev/null 2>&1 && [[ -f "$skill_dir/scripts/anysearch_cli.py" ]]; then
    say "Running: python3 .../anysearch_cli.py doc"
    if python3 "$skill_dir/scripts/anysearch_cli.py" doc >/tmp/anysearch-verify.out 2>&1; then
      printf '  %s✓ entry test ok%s\n' "$GREEN" "$RESET"
    else
      warn "entry test failed — see /tmp/anysearch-verify.out"
    fi
  else
    warn "no CLI runtime found for verify; skip"
  fi
else
  note "No skill dir to verify (MCP-only install)."
fi

note "Key also saved at: $ANYSEARCH_HOME/.env"
note "Auth docs: https://www.anysearch.com/docs/auth"

finish
